#define PJMEDIA_HAS_VID_TOOLBOX_CODEC 1
#define PJMEDIA_HAS_VIDEO 1
#define PJMEDIA_VIDEO_DEV_HAS_SDL 1
#define PJMEDIA_VIDEO_DEV_SDL_HAS_OPENGL    1
#define PJMEDIA_VIDEO_DEV_HAS_DSHOW 0
#define PJMEDIA_HAS_FFMPEG 1
#undef PJMEDIA_USE_OLD_FFMPEG
#define  FF_INPUT_BUFFER_PADDING_SIZE   32
